
export const SET_SCREEN_LAYOUT = 'SET_SCREEN_LAYOUT'

export const FILE_SHARE_DRAG_OVER = 'FILE_SHARE_DRAG_OVER'
export const FILE_SHARE_ADD_FILES = 'FILE_SHARE_ADD_FILES'

export const SIGNED_SHARE_ADD_FILES = 'SIGNED_SHARE_ADD_FILES'

export const SELECT_MEETING_VIEW = 'SELECT_MEETING_VIEW'
export const SELECT_EDITOR_FILE = 'SELECT_EDITOR_FILE'
export const SET_EDIT_SYNC_DATA = 'SET_EDIT_SYNC_DATA'

export const SET_MEETING_CONTEXT = 'SET_MEETING_CONTEXT'
export const SET_LOCAL_MEDIA_SOURCE = 'SET_LOCAL_MEDIA_SOURCE'
export const SET_LOCAL_SCREEN_SOURCE = 'SET_LOCAL_SCREEN_SOURCE'
export const SET_SCREEN_SHARING_STATUS = 'SET_SCREEN_SHARING_STATUS'

export const SEND_MESSAGE_START = 'SEND_MESSAGE_START'
export const SEND_MESSAGE_SUCCESS = 'SEND_MESSAGE_SUCCESS'
export const SEND_MESSAGE_ERROR = 'SEND_MESSAGE_ERROR'

export const CLEAR_NOTIFICATIONS = 'CLEAR_NOTIFICATIONS'

export const ROOM_EVENT = 'ROOM_EVENT'
export const PEER_EVENT = 'PEER_EVENT'
export const CALL_EVENT = 'CALL_EVENT'
export const STATE_SYNC_EVENT = 'STATE_SYNC_EVENT'
export const FILE_SHARE_EVENT = 'FILE_SHARE_EVENT'
export const SIGNED_SHARE_EVENT = 'SIGNED_SHARE_EVENT'
export const EDIT_SYNC_EVENT = 'EDIT_SYNC_EVENT'

export const TOGGLE_AUDIO = 'TOGGLE_AUDIO'
export const TOGGLE_VIDEO = 'TOGGLE_VIDEO'
export const TOGGLE_CHAT = 'TOGGLE_CHAT'

export const TOGGLE_RECORDING = 'TOGGLE_RECORDING'
export const SET_LOCAL_RECORDER_SOURCE = 'SET_LOCAL_RECORDER_SOURCE'

export const EDIT_SYNC_SET_FILE = 'EDIT_SYNC_SET_FILE'
export const EDIT_SYNC_EDIT = 'EDIT_SYNC_EDIT'
export const EDIT_SYNC_RENDER_START = 'EDIT_SYNC_RENDER_START'
export const EDIT_SYNC_RENDER_SUCCESS = 'EDIT_SYNC_RENDER_SUCCESS'
export const EDIT_SYNC_RENDER_ERROR = 'EDIT_SYNC_RENDER_ERROR'

export const ON_SHOW_MEETING_MODAL = 'ON_SHOW_MEETING_MODAL'
